# Generated by Django 2.0.4 on 2018-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('VIGILANTE', 'VIGILANTE')], max_length=20, unique=True),
        ),
    ]
